version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
  test1:
    steps:
      - run: echo test1
  test2:
    steps:
      - run: echo test2
  test3:
    steps:
      - run: echo test3

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
      - test3
