version: 2

jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
  test1:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run: echo test1
  test2:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run: echo test2
  test3:
    docker:
      - image: circleci/ruby:2
    steps:
      - run: echo test3
      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
      - test3
